In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
# Load dataset Iris dari scikit-learn
iris = load_iris()

##### Penjelasan:
1. import numpy as np -> mengimpor NumPy untuk melakukan pengolahan data dalam bnetuk array
2. import pandas as pd -> Mengimpor Pandas untuk menolah dan menampilkan data dalam bentuk tabel
3. from sklearn.datasets import load_iris -> Mengimpor fungsi load_iris dari scikit-learn untuk mengambil dataset iris
4. iris = load_iris() → Memuat dataset Iris dan menyimpannya ke dalam variabel iris agar dapat digunakan untuk proses klasifikasi selanjutnya.

In [2]:
#konversi data menjadi dataframe pandas
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df["Species"] = iris.target_names[iris.target]

#defenisikan X (fitur) dan y (target/label)
X = df.drop(columns=["Species"])
y = df["Species"]

print(X)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]


##### Penjelasan
1. pd.DataFrame(...) → Mengubah data Iris menjadi DataFrame dan menggunakan nama fitur sebagai nama kolom.
2. df["Species"] → Menambahkan kolom Species yang berisi jenis bunga Iris.
3. X = df.drop(...) → Menentukan X sebagai data fitur dengan menghapus kolom Species.
4. y = df["Species"] → Menentukan y sebagai target atau label berupa jenis bunga.
5. print(X) → Menampilkan data fitur yang digunakan dalam proses klasifikasi.

In [3]:
y

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: Species, Length: 150, dtype: str

##### Penjelasan
y : menampilkan isi label. Terlihat masih berupa teks (setosa, virginica, dst.) dengan tipe data object.

In [4]:
from sklearn.preprocessing import LabelEncoder
lab = LabelEncoder()
y = lab.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

##### Penjelasan
1. lab = LabelEncoder() : membuat objek encoder.
2. y = lab.fit_transform(y) : mempelajari kategori lalu mengubahnya menjadi angka:
setosa → 0
versicolor → 1
virginica → 2
3. Output berupa array berisi 0, 1, 2 (masing-masing 50 data).

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test = train_test_split(X, test_size=0.2, random_state=0)
y_train, y_test = train_test_split(y, test_size=0.2, random_state=0)

##### Penjelasan
1. test_size=0.2 : 20% data (30 data) untuk testing, 80% (120 data) untuk training.
2. random_state=0 : mengunci pengacakan agar pembagian selalu sama setiap dijalankan (hasil bisa direproduksi).

In [6]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
NB_model = model.fit(X_train, y_train)

##### Penjelasan
1. from sklearn.naive_bayes import GaussianNB : mengimpor algoritma Gaussian Naïve Bayes.
2. model = GaussianNB() : membuat model kosong.
3. model.fit(X_train, y_train) : melatih model. Ia menghitung rata-rata (μ) dan standar deviasi (σ) tiap fitur untuk tiap kelas, serta probabilitas awal kelas P(C).
4. NB_model : menyimpan model yang sudah terlatih.

In [7]:
result = NB_model.predict(X_test)
result

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0])

##### Penjelasan
NB_model.predict(X_test) : model memprediksi kelas untuk 30 data testing.

In [8]:
from sklearn.metrics import accuracy_score
print('Accuracy of data testing: ', accuracy_score(y_test, result)*100)

Accuracy of data testing:  96.66666666666667


##### Penjelasan
1. accuracy_score(y_test, result) : membandingkan label asli (y_test) dengan hasil prediksi (result).
2. *100 : mengubah ke persen.
3. Hasil: 96,67%, artinya 29 dari 30 data testing diprediksi benar.

In [9]:
#prediksi inputan data baru
#input_data = pd.DataFrame(np.array([[5.1, 3.5, 1.4, 0.2]]), columns=iris.feature_names)
input_data = [[5.1, 3.5, 1.4, 0.2]]
result = NB_model.predict(input_data)
prediction_label = lab.inverse_transform(result)
print('Hasil prediksi untuk input baru adalah:', prediction_label)

Hasil prediksi untuk input baru adalah: ['setosa']


c:\Users\HP\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2830: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


##### Penjelasan
1. input_data = [[5.1, 3.5, 1.4, 0.2]] : data bunga baru dalam bentuk list (satu baris, empat fitur).
2. NB_model.predict(input_data) : model memprediksi kelas data baru, hasilnya berupa angka.
3. lab.inverse_transform(result) : mengubah angka kembali menjadi nama spesies.

In [10]:
input_data = pd.DataFrame(np.array([[5.1, 3.5, 1.4, 0.2]]), columns=iris.feature_names)
result = NB_model.predict(input_data)
prediction_label = lab.inverse_transform(result)
print('Hasil prediksi untuk input baru adalah:', prediction_label)

Hasil prediksi untuk input baru adalah: ['setosa']


##### Penjelasan
1. pd.DataFrame(np.array([[5.1, 3.5, 1.4, 0.2]]), columns=iris.feature_names) : membungkus input menjadi DataFrame dengan nama kolom yang sama seperti data training.
2. Langkah lainnya sama dengan In [9]: predict → inverse_transform → print.

TUGAS PRAKTIKUM

In [11]:
input_data = pd.DataFrame(np.array([[7.3, 3.8, 4.6, 2.3]]), columns=iris.feature_names)

result = NB_model.predict(input_data)
prediction_label = lab.inverse_transform(result)
print('Hasil prediksi untuk input baru adalah:', prediction_label)

# (Opsional) lihat probabilitas tiap kelas
print(NB_model.predict_proba(input_data))

Hasil prediksi untuk input baru adalah: ['virginica']
[[4.83048542e-194 3.68081469e-007 9.99999632e-001]]


##### Penjelasan
1. Bungkus input menjadi DataFrame dengan columns=iris.feature_names agar konsisten dengan data training dan tidak muncul warning.
2. NB_model.predict(input_data) menghasilkan kelas dalam bentuk angka, yaitu 2.
3. lab.inverse_transform(result) mengubah angka tersebut menjadi nama spesies.